version: '3'

services:
  db:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    #environment:
    #  - "MYSQL_ROOT_PASSWORD=123456"
    env_file: common.env
# OPCIONAL
# volumes:

#OPCIONAL
# networks:
